FROM node:14.17.4-alpine

# vi tri thu muc 
WORKDIR /app

COPY package.json ./

COPY . .

RUN yarn

RUN yarn build

RUN rm -rf /app/node_modules

# cau lenh run
RUN yarn install --production

EXPOSE 3000

CMD [ "yarn", "start" ]