export const REQUEST_SPINNER_STARTED = "spinner/REQUEST_SPINNER_STARTED";
export const REQUEST_SPINNER_ENDED = "spinner/REQUEST_SPINNER_ENDED";
export const REQUEST_RESET_SPINNER = "spinner/REQUEST_RESET_SPINNER";
