version: "3.9"

services:
  client:
    stdin_open: true
    container_name: client
    restart: always
    image: xaythixin/images:english.prod.fe.latest
    ports:
      - 3000:3000
    networks:
      - nw_tnms

networks:
  nw_tnms:
