FROM node:14.17.4-alpine as builder
WORKDIR /app
COPY ./package.json ./
RUN yarn install --production=true
COPY . .
RUN yarn build:staging

FROM nginx
EXPOSE 80
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm -rf /app