version: "3.9"

networks:
  nginx-network:

services:
  # mysql:
  #   container_name: mysql_english
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   image: mysql:8.0.26
  #   ports:
  #    - 3306:3306
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456788
  #     MYSQL_PASSWORD: 123456788
  #     MYSQL_DATABASE: cyber_english
  #     MYSQL_USER: cyberEnglishProd
  #   networks:
  #     - nginx-network

  # client:
  #   stdin_open: true
  #   container_name: client_english
  #   restart: always
  #   image: xaythixin/images:english.prod.fe.latest
  #   ports:
  #    - 3000:3000
  #   depends_on:
  #     - mysql
  #   networks:
  #     - nginx-network

  api:
    container_name: api_english
    restart: always
    # image: xaythixin/images:english.prod.be.latest
    build: .
    volumes: 
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - nginx-network
    environment:
      MYSQL_DATABASE: cyber_english
      MYSQL_HOST: 139.59.116.127
      MYSQL_USER: root
      MYSQL_PASSWORD: h8U1q59DZjsQCo1u
      MYSQL_PORT: 3306
      MYSQL_CONNECTIONLIMIT: 10
      SERVER_HOSTNAME: https://beeng.cybersoft.edu.vn
      SERVER_PORT: 3000
      SERVER_DOMAIN_ASSETS: https://beeng.cybersoft.edu.vn
      URL_CHECK_LOGIN: https://apicrm.cybersoft.edu.vn/api
      ASSETS_PORT: 3000
      LOG_DIR: "/logs"
      LOG_LEVEL: "info"
      NODE_ENV: "production"
